import { HeaderBrand } from "@/components/HeaderBrand";
import { Button } from "@/components/ui/button";
import { ADVICE_DISCLAIMER_SHORT } from "@/lib/disclaimer";
import {
  LEGAL_ADDRESS,
  LEGAL_COUNTRY,
  LEGAL_OPERATOR,
  LEGAL_REGISTRY_CODE,
  LEGAL_VAT_ID,
  PRODUCT_CONTACT_EMAIL,
  PRODUCT_NAME,
  PRODUCT_SUPPORT_EMAIL,
} from "@/lib/product";
import Link from "next/link";
import { publicPageMetadata } from "@/lib/site-metadata";
import type { ReactNode } from "react";

export const metadata = publicPageMetadata({
  title: "Terms of Service",
  description: "The rules for using Upside Lab.",
  path: "/terms",
});

export default function TermsPage() {
  return (
    <div className="min-h-dvh bg-background text-foreground">
      <header className="border-b border-border bg-background/90 backdrop-blur">
        <div className="mx-auto flex max-w-3xl items-center justify-between gap-3 px-4 py-3">
          <HeaderBrand />
          <Button asChild variant="outline" size="sm">
            <Link href="/">Back</Link>
          </Button>
        </div>
      </header>

      <main id="main" className="flex flex-col mx-auto min-w-0 max-w-3xl gap-6 px-6 py-10 text-sm leading-relaxed text-foreground">
        <div>
          <h1 className="text-2xl font-semibold text-foreground">Terms of Service</h1>
          <p className="mt-1 text-sm text-muted-foreground">Last updated {LAST_UPDATED}</p>
        </div>

        <p>
          These terms cover your use of {PRODUCT_NAME} (&ldquo;the app,&rdquo;
          &ldquo;we,&rdquo; &ldquo;us&rdquo;). By creating an account or
          signing in, you agree to them.
        </p>

        <Section title="1. Who we are">
          {PRODUCT_NAME} is operated by {LEGAL_OPERATOR}, a private limited
          company in {LEGAL_COUNTRY} (registry code {LEGAL_REGISTRY_CODE}).
          Registered office: {LEGAL_ADDRESS}. VAT ID {LEGAL_VAT_ID}. Questions:{" "}
          <a
            href={`mailto:${PRODUCT_CONTACT_EMAIL}`}
            className="underline hover:text-foreground"
          >
            {PRODUCT_CONTACT_EMAIL}
          </a>
          .
        </Section>

        <Section title="2. Not financial advice">
          {ADVICE_DISCLAIMER_SHORT} {PRODUCT_NAME} is a tracking and planning
          tool. Numbers, targets, forecasts, and anything generated by the AI
          assistant (&ldquo;Margus&rdquo;) or other AI features are not tax or
          legal advice either. You are solely responsible for your own
          investment decisions. Markets carry real risk, and you can lose
          some or all of the money you put in. Covered calls and other
          options carry extra risks of their own. A licensed professional
          can advise on your own situation.
        </Section>

        <Section title="3. Your account">
          You sign in with Google, or with a link we send to your email.
          There is no password. You can connect more than one email address
          to one account, and after that any of them opens the same account
          with the same portfolios. You&apos;re responsible for keeping
          those Google accounts and mailboxes secure. Anyone with access to
          one of them can access your{" "}
          {PRODUCT_NAME} data. Under 13 is never allowed. If you sign up on
          your own, you confirm you are 16 or older when you sign in. If a
          teacher invited you into a Classroom, the age is 13, because a
          class is run by a school and uses pretend money only. Classroom is
          a teacher-invite paper class (see below), not a brokerage.
        </Section>

        <Section title="4. The supporter plan">
          <p>
            <strong className="text-foreground">
              The supporter plan gets you nothing extra.
            </strong>{" "}
            Every part of {PRODUCT_NAME} works the same whether you pay or
            not. It is twelve euros a month, it renews every month until you
            stop it, and it is a way to help pay for building this. The
            checkout screen says the same thing, and this section is here so
            the contract says it too.
          </p>
          <p>
            Stripe takes the payment. Your card details go to Stripe and we
            never see or store your card number. The price on the checkout
            screen is the price charged.
          </p>
          <p>
            Stop it whenever you like from{" "}
            <Link href="/account" className="underline hover:text-foreground">
              My account
            </Link>
            , which opens Stripe&apos;s billing page. Stopping keeps the plan
            running to the end of the month you have already paid for, and
            does not refund that month.
          </p>
          <p>
            If you live in the EU, you have 14 days from the day you start to
            change your mind and get that first payment back. EU law lets a
            seller ask you to give up those 14 days for something delivered
            to you straight away, and we do not ask, because there is no
            feature being delivered. Write to us inside those 14 days and we
            will refund the first charge. If a charge ever looks wrong to
            you, write to us and we will sort it out.
          </p>
          <p>
            VAT is included in the price where it applies. We handle EU VAT
            through the One Stop Shop, which is the arrangement that lets one
            country&apos;s tax office collect VAT for the whole EU on our
            behalf. If you have a valid EU business VAT number, Stripe asks
            for it at checkout and no VAT is added.
          </p>
        </Section>

        <Section title="5. Classroom">
          A teacher can invite a class into a private paper Classroom. Each
          student gets homework cash and an empty portfolio. It is not a real
          brokerage, not real money, and not a real account. A real portfolio
          cannot be shared into a class. The teacher sets when buying and selling
          are allowed. If you are a student, you join only with that invite.
          If your country needs a parent or guardian for someone your age to
          use an app like this, that person has to agree. The teacher is
          responsible for running the class under their school&apos;s rules.
        </Section>

        <Section title="6. Your data, your entries">
          You keep ownership of the portfolio data you enter (holdings, cash,
          notes, thesis text). You&apos;re responsible for its accuracy; we
          don&apos;t verify anything you type in. If you invite a co-owner to
          a portfolio, they can read and edit everything on it, though only
          the person who made the portfolio can delete it or remove another
          co-owner. If you join a circle, members can see today&apos;s
          prices, the companies you hold, cash, and returns for the
          portfolios you linked. They do not see
          what you paid unless you also made them a co-owner. If two
          accounts are linked as a household, Circle join, leave, and role
          copy to both. Classroom stays per person. Don&apos;t enter data you
          don&apos;t have the right to share with those people.
        </Section>

        <Section title="7. Market data and third parties">
          Prices, quotes, options chains, earnings dates, and seasonality
          stats come from third-party data providers on a best-effort,
          &ldquo;as available&rdquo; basis. We do not run a licensed
          exchange feed. Data can be delayed, incomplete, estimated when a
          live feed is unavailable, or wrong. We mark data as out of date or
          estimated where we can tell, but we make no accuracy or
          availability guarantee. AI features call third-party model
          providers. Some of those providers process data outside{" "}
          {LEGAL_COUNTRY}, including the United States. Your own account and
          portfolio data is stored in the European Union; the privacy policy
          says who else touches it. If every provider is temporarily
          unavailable, that feature stops working rather than the rest of
          the app.
        </Section>

        <Section title="8. Acceptable use">
          Don&apos;t attempt to break, scrape at abusive volume, reverse
          engineer for competitive cloning, or use the app to store data you
          don&apos;t have rights to. Don&apos;t use it to provide financial
          advice to third parties under our name. We may suspend accounts
          that abuse shared infrastructure (for example, hammering the AI or
          market-data endpoints in a way that degrades service for others).
        </Section>

        <Section title="9. Availability">
          This is a small, evolving product. We don&apos;t guarantee uptime,
          and features can change, be renamed, or be removed as the app
          develops. We take reasonable care with backups but you can export
          your own data at any time from{" "}
          <Link href="/account" className="underline hover:text-foreground">
            My account
          </Link>
          , so please don&apos;t treat {PRODUCT_NAME} as your only record of
          anything important.
        </Section>

        <Section title="10. Liability">
          {PRODUCT_NAME} is provided &ldquo;as is,&rdquo; without warranties of
          any kind, except where the law of {LEGAL_COUNTRY} or your EU
          consumer rights say we cannot disclaim them. To the maximum extent
          permitted by law, we aren&apos;t liable for trading losses, missed
          gains, data loss, or any decision made using information from the
          app. If you are an EU consumer, you keep the mandatory protections
          of your home country.
        </Section>

        <Section title="11. Governing law">
          These terms are governed by the laws of {LEGAL_COUNTRY}. Courts in{" "}
          {LEGAL_COUNTRY} have jurisdiction, except that EU consumers may
          also bring a claim in their home country where the law gives them
          that right.
        </Section>

        <Section title="12. Changes">
          We may update these terms as the product changes. Material changes
          will be reflected here with a new &ldquo;last updated&rdquo; date.
          Continuing to use {PRODUCT_NAME} after a change means you accept the
          update.
        </Section>

        <Section title="13. Contact">
          Product help:{" "}
          <a
            href={`mailto:${PRODUCT_SUPPORT_EMAIL}`}
            className="underline hover:text-foreground"
          >
            {PRODUCT_SUPPORT_EMAIL}
          </a>
          . Questions about these terms:{" "}
          <a
            href={`mailto:${PRODUCT_CONTACT_EMAIL}`}
            className="underline hover:text-foreground"
          >
            {PRODUCT_CONTACT_EMAIL}
          </a>
          .
        </Section>

        <p className="pt-4 text-sm text-muted-foreground">
          See also our{" "}
          <Link href="/privacy" className="underline hover:text-foreground">
            Privacy policy
          </Link>
          .
        </p>
      </main>
    </div>
  );
}

const LAST_UPDATED = "2 September 2026";

function Section({
  title,
  children,
}: {
  title: string;
  children: ReactNode;
}) {
  return (
    <section className="flex flex-col gap-2">
      <h2 className="font-semibold text-foreground">{title}</h2>
      {/*
        A div rather than a p, so a section that needs more than one
        paragraph can have them. Section 4 was a single 200-word block
        covering the price, the card, cancelling the plan, the EU right to
        change your mind, and VAT, which is five different questions read
        as one breath.

        An ordinary block, never a flex column: most sections here are one
        run of prose with a mail link in the middle of it, and a flex
        container turns every stretch of bare text into an item of its own,
        so "Questions:", the address, and the full stop after it each land
        on their own line. The parent spaces its paragraphs instead, so no
        paragraph carries its own margin.
      */}
      <div className="[&>p+p]:mt-3">{children}</div>
    </section>
  );
}
